# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: no

  mongo-express:
    image: mongo-express
    restart: no
    ports:
      - 8081:8081

  jupyter:
    container_name: jupyter10
    build:
      context: ./jupyter
    restart: no
    ports:
      - 8888:8888
    user: root
    volumes:
      - ./:/home/jovyan
    command: ["start.sh", "jupyter", "lab", "--NotebookApp.token=''"]