version: "3.2"

services:
  jupyter:
    container_name: jupyter
    image: jupyter/base-notebook
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
    command: ["start.sh", "jupyter", "lab", "--NotebookApp.token=''"]

  neo4j:
    container_name: neo4j
    image: neo4j:5.14
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
